#!/bin/sh

set -eo pipefail


#======================================================================================================================
# Set bcg- executables as, well, executable
#======================================================================================================================

chmod +x /usr/local/bin/bcg-*


#======================================================================================================================
# Ensure target platform is set
#======================================================================================================================

[[ -z "${TARGETPLATFORM-}" ]] && bcg-error "Target platform not set."


#======================================================================================================================
# Get correct installer for target platform
#======================================================================================================================

case "${TARGETPLATFORM}" in

    "linux/amd64")
        ARCH="amd64"
        ;;

    "linux/arm/v7")
        ARCH="armhf"
        ;;

    "linux/arm64")
        ARCH="aarch64"
        ;;

    *)
        bcg-error "Unsupported target platform: ${TARGETPLATFORM}."
        ;;

esac


#======================================================================================================================
# Download and run S6 installer
#======================================================================================================================

cd /tmp

S6_VERSION=$(cat S6_VERSION)
bcg-echo "S6 Overlay v${S6_VERSION}"

S6_URL="https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${ARCH}-installer"
bcg-echo "Downloading ${S6_URL}..."
wget -O installer ${S6_URL} && chmod +x installer
bcg-done

bcg-echo "Installing S6 Overlay..."
./installer /

[[ -d /etc/s6 ]] && bcg-done || bcg-error "S6 Overlay not installed."


#======================================================================================================================
# Install esh template engine
#======================================================================================================================

bcg-echo "Installing esh..."
apk add --no-cache esh && bcg-done || bcg-error "esh not installed."


#======================================================================================================================
# Set timezone
#======================================================================================================================

bcg-tz "Europe/London"
