#!/bin/sh

source /etc/profile.d/functions.sh

#======================================================================================================================
# Check for target platform
#======================================================================================================================

if [ -z "${TARGETPLATFORM}" ] ; then
    _x " - target platform not set."
fi


#======================================================================================================================
# Get correct installer for target platform
#======================================================================================================================

case "${TARGETPLATFORM}" in
    "linux/amd64")
        INSTALLER="s6-overlay-amd64-installer"
        ;;
    "linux/arm/v7")
        INSTALLER="s6-overlay-armhf-installer"
        ;;
    "linux/arm64")
        INSTALLER="s6-overlay-aarch64-installer"
        ;;
    *)
esac

if [ -z "${INSTALLER}" ] ; then
    _x " - unsupported target platform: ${TARGETPLATFORM}"
fi


#======================================================================================================================
# Download and run installer
#======================================================================================================================

cd /tmp

URL="https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/${INSTALLER}"
_e " - downloading ${URL}"
wget -O ${INSTALLER} ${URL} && chmod +x ${INSTALLER}
_d

_e " - installing S6 v${S6_VERSION}"
./${INSTALLER} /

if [ -d /etc/s6 ] ; then
    _d
    exit 0
else
    _x "S6 not installed"
fi
