#!/bin/sh

#======================================================================================================================
# Get correct installer for target platform
#======================================================================================================================

case "${TARGETPLATFORM}" in
    "linux/amd64")
        INSTALLER="s6-overlay-amd64-installer"
        ;;
    "linux/arm/v7")
        INSTALLER="s6-overlay-armhf-installer"
        ;;
    "linux/arm64")
        INSTALLER="s6-overlay-aarch64-installer"
        ;;
    *)
esac

if [ -z "${INSTALLER}" ] ; then
    echo "Unsupported target platform: ${TARGETPLATFORM}"
    exit 1
fi


#======================================================================================================================
# Download and run installer
#======================================================================================================================

cd /tmp

URL="https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/${INSTALLER}"
echo " - downloading ${URL}..."
wget -O ${INSTALLER} ${URL} && chmod +x ${INSTALLER}
echo " - done."

echo " - installing S6 v${S6_VERSION}..."
./${INSTALLER} /

if [ -d /etc/s6 ] ; then
    echo " - done."
    exit 0
else
    echo " - error."
    exit 1
fi
