#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Forward cron log to Docker.
#======================================================================================================================

[[ ! -f ${BF_CRON_LOG_FILE} ]] && touch ${BF_CRON_LOG_FILE}
bf-forward ${PWD##*/} ${BF_CRON_LOG_FILE}
