#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E="cron-log/$(basename ${0})"


#======================================================================================================================
# Forward cron log to Docker.
#======================================================================================================================

[[ ! -f ${CRON_LOG_FILE} ]] && touch ${CRON_LOG_FILE}
bcg-forward "cron-log" ${CRON_LOG_FILE}
