#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

SCRIPTS=/etc/scripts
bcg-env "SCRIPTS" "${SCRIPTS}"
bcg-env "SCRIPTS_INC" "${SCRIPTS}/inc"

bcg-env "CRON_LOG_FILE" "/var/log/cron.log"
bcg-env "S6_SERVICES" "/var/run/s6/services"
