#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

LIB=/usr/lib/bf
bf-env "BF_LIB" "${LIB}"
bf-env "BF_INC" "${LIB}/inc"

ETC=/etc/bf
bf-env "BF_TEMPLATES" "${ETC}/templates"
bf-env "BF_SRC" "${ETC}/src"

bf-env "CRON_LOG_FILE" "/var/log/cron.log"
bf-env "S6_SERVICES" "/var/run/s6/services"
