#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

LIB=/usr/lib/bcg
bcg-env "LIB" "${LIB}"
bcg-env "LIB_INC" "${LIB}/inc"

bcg-env "CRON_LOG_FILE" "/var/log/cron.log"
bcg-env "S6_SERVICES" "/var/run/s6/services"

bcg-env "TEMPLATES" "/etc/templates"
