#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

bf-env "BF_IMAGE" `cat /BF_IMAGE`
bf-env "BF_VERSION" `cat /BF_VERSION`

LIB=/usr/lib/bf
bf-env "BF_LIB" "${LIB}"
bf-env "BF_INC" "${LIB}/inc"

ETC=/etc/bf
bf-env "BF_TEMPLATES" "${ETC}/templates"
bf-env "BF_SRC" "${ETC}/src"

bf-env "BF_CRON_LOG_FILE" "/var/log/cron.log"
