#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Start cron
#   -f  run in foreground mode (allows S6 to supervise the service - which keeps the container running)
#   -l  log level (from 0 to 8 - 0 is the most verbose)
#   -L  log to file (cron-log service will forward this file to the Docker log)
#======================================================================================================================

bcg-echo "Starting cron"
/usr/sbin/crond \
    -f \
    -l ${CRON_LOG_LEVEL} \
    -L ${CRON_LOG_FILE}
