#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Start cron
#   -f  run in foreground mode (allows S6 to supervise the service)
#======================================================================================================================

_echo "Starting cron"
/usr/sbin/crond -f
