#!/bin/withenv sh

set -euo pipefail


#======================================================================================================================
# Run preflight checks
#======================================================================================================================

nu -c "use bf-s6 run ; run preflight"


#======================================================================================================================
# Start cron in foreground mode.
# Flags:
#   -f  run in foreground mode (allows S6 to supervise the service - which keeps the container running)
#   -l  log level (from 0 to 8 - 0 is the most verbose)
#   -L  log to a file (instead of stdout)
#======================================================================================================================

crond -f -l ${BF_CRON_LOG_LEVEL} -L ${BF_CRON_LOG_FILE}
