#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Run container initialisation - if it fails, terminate the container.
#======================================================================================================================

bf-fix-attrs && bf-cont-init || bf-svc-terminate
