name: dev-alpine3_14

on:
  push:
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  test-alpine3_14:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Checkout shUnit2
        uses: actions/checkout@v2
        with:
          repository: kward/shunit2
          ref: v2.1.8
          path: ./shunit2
      -
        name: Run tests
        run: |
          RUN=./tests/run-git.sh && chmod +x ${RUN} && ${RUN}
  build-alpine3_14:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./3.14/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/alpine-s6:dev
            bfren/alpine-s6:alpine3.14-dev
            bfren/alpine-s6:alpine3.14-${{ steps.version_minor.outputs.contents }}-beta
            bfren/alpine-s6:alpine3.14-${{ steps.version.outputs.contents }}-beta
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
