name: publish-alpine3_13

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-alpine3_13:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read Alpine version - revision
        uses: bfren/read-file-action@v1
        with:
          path: ./3.13/ALPINE_REVISION
        id: alpine_revision
      -
        name: Read image version
        uses: bfren/read-file-action@v1
        with:
          path: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./3.13/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/alpine-s6:alpine3.13
            bfren/alpine-s6:alpine3.13-${{ steps.version_minor.outputs.content }}
            bfren/alpine-s6:alpine3.13-${{ steps.version.outputs.content }}
            bfren/alpine-s6:alpine${{ steps.alpine_revision.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
